### ISSUE TITLE
Pre-Loaded Hat v2.3 and Pi 3A+ Error Code 1900

### ISSUE THREAD

**Issue by covig0** [skipfire/genmon-addon#1]
I have a Generac 24k. I purchased the Pre-Loaded Hat v2.3 and Pi 3A+. When I disconnect the wiring harness and connect the Pi, the generator turns on and gives an error code 1900 (low voltage). If I disconnect the Pi, reconnect the harness, and reset the error code everything returns to normal. Is there a setting on genmon or the Hat that needs to be changed?

**Comment by skipfire** [comment]
That only happens when you install without using the included power cable.  If you connect the included power cable and then flip the GenPwr switch back to the off position it should not trigger the low voltage condition.

**Comment by covig0** [comment]
Thanks, skipfire. To clarify, when powering with the included power cable, connected to the generator battery, the switches are as follows?
Genpwr - off
Buck - on
W1 - off

**Comment by skipfire** [comment]
BUCK on and GENPWER off yes.  BUCK needs to be on when powering by Molex or barrel, GENPWR should only be on when powering by the Molex cable which should primarily be done only when using the injector.  Some Evo2s are able to power a 3A+ from the controller, and some are not, I've not found any way of predicting it.

W1 is unrelated to power and can be on or off.  It controls the 1-Wire connection to GPIO 04.  W1 off disables the onboard DS18B20 and the screw terminals that support external 1-Wire temp sensors.

**Comment by covig0** [comment]
Thanks, skipfire. It is working as designed. Now all I have to do is get a WAP out there so the wifi signal isn't -80.

**Comment by skipfire** [comment]
Do you have it inside the enclosure or outside?  If inside the enclosure, just moving it to a weatherproof plastic box on the outside of it on the house side can get you 10dB or more improvement.

**Comment by covig0** [comment]
It is outside the enclosure. It is just too far from the main house. I need to run a WAP on that side anyway. I have a Ubiquiti set up with a UDM Pro and switch. It's just a matter of running the CAT6. Thanks again.
