### ISSUE TITLE
Increased board temp after updating to ESPHome 2024.7.0

### ISSUE THREAD

**Issue by gmn42** [skipfire/genmon-addon#4]
This is mostly informational, but I just updated my bridge board to ESPHome 2024.7.0 and noticed the reported temperature immediately went up by about 5 degrees F.  I assume it is due to increased power consumption in the new version of the firmware.  Communication still seems to be working correctly, but I figured it should be reported.  I haven't measured the actual current draw or tried to figure out if it might be an issue with battery drain overnight when the generator is off during an outage.   Actual ambient is about 65 F, so it's heating up against a substantial gradient, but the sensor is inside the plastic case which will provide some insulation, so it might not actually be too bad.
![Screenshot from 2024-07-18 19-37-24](https://github.com/user-attachments/assets/55ed0e7e-0851-4617-907e-b2062df9446b)

**Comment by skipfire** [comment]
It's possible the workload of doing the deploy heated things up and it just hasn't had a temp differential big enough to  cool back down with between the plastic case and whatever enclosure it is in.  As for the battery, I have zero concern about the drain on the battery as even at max it just sips power compared to Raspberry Pi that the majority of genmon users are using.  My outdoor temps have been 80 to almost 100 with plenty of sun so my temp graphs are basically useless for trying to compare.
