### ISSUE TITLE
Issue installing yaml on ESPHome 2024.6.0 + 

### ISSUE THREAD

**Issue by jfolli1** [skipfire/genmon-addon#5]
Need to update the ota: section of the yaml with a platform: esphome to satisfy the latest version of ESPhome

"In release 2024.6.0, the ota component transitioned from a standalone component to a platform component. This change was made to facilitate the use of multiple update mechanisms, enabling greater flexibility."

https://next.esphome.io/components/ota/

**Comment by skipfire** [comment]
@jfolli1 thanks for letting me know, I'll get that updated today once I've had a chance to test the changes.

**Comment by skipfire** [comment]
@jfolli1 I believe all of the config yamls have been updated as necessary.  The original OGS board also had onboard temp chip that needed config changes.
