### ISSUE TITLE
OpenGenSet Drops Connection

### ISSUE THREAD

**Issue by npotternyc** [skipfire/genmon-addon#6]
My OpenGenSet runs for about an hour when attached to my generator, then loses the connection.  This is what my config looks like:
```

esphome:
  name: genmon-rs232-bridge
  friendly_name: Genmon-RS232-Bridge

substitutions:
  display_name: GenMon RS232 Bridge

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  # Disable serial logging
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "XXXX"

ota:
  - platform: esphome
    password: "XXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  reboot_timeout: 5min

  manual_ip:
    static_ip: 192.168.10.154
    gateway: 192.168.10.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Genmon-RS232-Bridge"
    password: "XXXX"

captive_portal:
  
# Individual sensors
sensor:
  - platform: wifi_signal
    name: "$display_name WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "$display_name IP Address"
  - platform: version
    name: "$display_name ESPHome Version"

web_server:
  port: 80
  include_internal: true
  
switch:
  - platform: restart
    name: "$display_name Restart"

external_components:
  - source: github://skipfire/esphome-stream-server
    refresh: 0s

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: 22
  rx_pin: 23
  debug:
    direction: BOTH
    after:
      timeout: 100ms
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');   

stream_server:
   uart_id: uart_bus
   port: 6638

binary_sensor:
  - platform: stream_server
    connected:
      name: "$display_name Client Connected"
    
```

**Comment by skipfire** [comment]
Is it dropping off wifi, or just no longer connecting to genmon?

Has it been doing it since your purchase, or is this new behavior?

Is the antenna inside or outside the generator?

**Comment by npotternyc** [comment]
I bought it in May but have only been able to set it up this month. It had been doing this the whole time. 

It is dropping off the WiFi completely, I can't get to the embedded web page.

I moved the antenna outside the enclosure and repositioned my WiFi extender to improve the connection, it's about -69db.

**Comment by skipfire** [comment]
-69dB is a pretty weak signal and is most likely the problem.

**Comment by npotternyc** [comment]
Disappointing. I have lots of other IOT devices on my network with weaker signals and no problem staying connected.

**Comment by skipfire** [comment]
OpenGenSet uses a common ESP32 device, however it is installed outside the house which means exterior walls that have much more construction in them, and the unit is placed in or against a metal object.  I was able to take mine about 200 feet away from my house (on a battery pack) and have it maintain connection, but when I put it on the back of my generator 15 feet from the closest WAP it had about the same signal strength as when it was 150 feet away.  I have also sent a message to the email on the order about a resolution option.

**Comment by npotternyc** [comment]
I was able to get it to stay connected by switching my 2.4 ghz network to channel 1 and swapping out the molex cable.

**Comment by skipfire** [comment]
Thanks for sharing, it's been a long time since I've had to pay attention to WiFi channel so I didn't even consider that option.  I'm glad you have a stable connection now.
